<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\AllSetting;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Database\Seeders\DistrictSeeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Omar Shohag',
            'email' => 'omarshohag93@gmail.com',
        ]);


        $this->call([
            DistrictSeeder::class,
        ]);

        $settingsData = [
            // 1 = Religion
            1 => ['Islam', 'Hindus', 'Buddhists', 'Christianity', 'Other Religions'],

            // 2 = Occupation
            2 => [
                'Housewife', 'Farmer', 'Day Labour', 'Business', 'Student',
                'Govt. Service', 'Private Service', 'Others',
                'Garments Worker', 'Journalist'
            ],

            // 3 = Education Status
            3 => [
                'Primary', 'Secondary', 'SSC', 'HSC',
                'Graduate', 'Illiterate', 'Post graduate', 'Masters'
            ],

            // 4 = Monthly Income
            4 => ['<< 5000', '<< 7000', '<< 10000', '<< 15000', '<< 20000', '>> 20000'],

            // 5 = Blood Group
            5 => ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],

            // diagnosis
            6 => ['Lower Abdominal Pain', 'Whole Abdominal Pain', 'Test Infos', 'Test Infos 2'],

            // C/F
            7 => ['Pain ', 'Body Pain', 'Whole Pain'],

            // Name of Operation
            8 => ['Major Operation', 'Minor Operation', 'Gastric Operation', 'Other Operation'],

             // Doctor Designation
            9 => ['Professor', 'Association Professor', 'Assistant Professor', 'Senior Consultant',  'Consultant', 'Doctor', 'Other']
        ];

        // Build and insert settings
        foreach ($settingsData as $type => $titles) {
            foreach ($titles as $index => $title) {
                AllSetting::create([
                    'title'         => $title,
                    'type'          => $type,
                    'display_order' => $index + 1,
                    'is_active'     => 1
                ]);
            }
        }


        DB::table('webpage_contents')->insert([
            [
                'id' => 1,
                'type' => 1,
                'icon' => '',
                'title' => 'Why Choose',
                'short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit Asperiores dolores sed et. Tenetur quia eos. Autem tempore quibusdam vel necessitatibus optio ad corporis.',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit Asperiores dolores sed et. Tenetur quia eos. Autem tempore quibusdam vel necessitatibus optio ad corporis.',
                'storage_type' => '1',
                'file_path' => NULL,
                'display_position' => 1,
                'is_highlight_item' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:04:09',
                'updated_at' => '2025-08-23 01:04:09',
            ],
            [
                'id' => 2,
                'type' => 1,
                'icon' => 'bi bi-clipboard-data',
                'title' => 'Corporis voluptates officia eiusmod',
                'short_description' => 'Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip',
                'description' => 'Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip',
                'storage_type' => '1',
                'file_path' => NULL,
                'display_position' => 2,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:04:52',
                'updated_at' => '2025-08-23 01:04:52',
            ],
            [
                'id' => 3,
                'type' => 1,
                'icon' => 'bi bi-gem',
                'title' => 'Ullamco laboris ladore pan',
                'short_description' => 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt',
                'description' => 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt',
                'storage_type' => '1',
                'file_path' => NULL,
                'display_position' => 2,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:06:00',
                'updated_at' => '2025-08-23 01:06:00',
            ],
            [
                'id' => 4,
                'type' => 1,
                'icon' => 'bi bi-inboxes',
                'title' => 'Labore consequatur incidid dolore',
                'short_description' => 'Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere',
                'description' => 'Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere',
                'storage_type' => '1',
                'file_path' => NULL,
                'display_position' => 4,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:06:31',
                'updated_at' => '2025-08-23 01:06:31',
            ],
            [
                'id' => 5,
                'type' => 2,
                'icon' => '',
                'title' => 'About Us',
                'short_description' => 'Dolor iure expedita id fuga asperiores qui sunt consequatur minima. Quidem voluptas deleniti. Sit quia molestiae quia quas qui magnam itaque veritatis dolores. Corrupti totam ut eius incidunt reiciendis veritatis asperiores placeat.',
                'description' => 'Dolor iure expedita id fuga asperiores qui sunt consequatur minima. Quidem voluptas deleniti. Sit quia molestiae quia quas qui magnam itaque veritatis dolores. Corrupti totam ut eius incidunt reiciendis veritatis asperiores placeat.',
                'storage_type' => '1',
                'file_path' => 'uploads/UE6Ry0AipVwIW8SkTAQhXPqUovN1z1M3ZLU1QBO1.jpg',
                'display_position' => 1,
                'is_highlight_item' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:12:23',
                'updated_at' => '2025-08-23 01:12:23',
            ],
            [
                'id' => 6,
                'type' => 2,
                'icon' => 'fa-solid fa-vial-circle-check',
                'title' => 'Ullamco laboris nisi ut aliquip consequat',
                'short_description' => 'Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade',
                'description' => 'Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade',
                'storage_type' => '1',
                'file_path' => 'uploads/VZ2SmYrrPZPegK8JFJO2IwH8C455dOTDfGJn0sOI.jpg',
                'display_position' => 2,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:13:28',
                'updated_at' => '2025-08-23 01:13:28',
            ],
            [
                'id' => 7,
                'type' => 2,
                'icon' => '',
                'title' => 'Magnam soluta odio exercitationem reprehenderi',
                'short_description' => 'Quo totam dolorum at pariatur aut distinctio dolorum laudantium illo direna pasata redi',
                'description' => 'Quo totam dolorum at pariatur aut distinctio dolorum laudantium illo direna pasata redi',
                'storage_type' => '1',
                'file_path' => 'uploads/l5lgu4IqyG96F82HFmjIUBTrnK9MwFf3u9rKkxUj.jpg',
                'display_position' => 3,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:13:59',
                'updated_at' => '2025-08-23 01:13:59',
            ],
            [
                'id' => 8,
                'type' => 2,
                'icon' => '',
                'title' => 'Voluptatem et qui exercitationem',
                'short_description' => 'Et velit et eos maiores est tempora et quos dolorem autem tempora incidunt maxime veniam',
                'description' => 'Et velit et eos maiores est tempora et quos dolorem autem tempora incidunt maxime veniam',
                'storage_type' => '1',
                'file_path' => 'uploads/1EyYlV6MyPy0ZeTVFHrj5mJv9JfKnpLWqaxWyupW.jpg',
                'display_position' => 4,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:14:20',
                'updated_at' => '2025-08-23 01:14:20',
            ],
            [
                'id' => 9,
                'type' => 3,
                'icon' => '',
                'title' => 'Stomach Cancer',
                'short_description' => 'Treatment and consultation for stomach (gastric) cancer.',
                'description' => 'Treatment and consultation for stomach (gastric) cancer.',
                'storage_type' => '1',
                'file_path' => 'uploads/c3tuGRnFIU9nhhiEsypq3uel8FcUk8oHMxZC8Tun.jpg',
                'display_position' => 1,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:16:24',
                'updated_at' => '2025-08-23 01:16:24',
            ],
            [
                'id' => 10,
                'type' => 3,
                'icon' => 'stretched-link',
                'title' => 'Esophageal Cancer',
                'short_description' => 'Comprehensive care for cancer of the esophagus.',
                'description' => 'Comprehensive care for cancer of the esophagus.',
                'storage_type' => '1',
                'file_path' => 'uploads/92huEqoFbN3IIqNGBv2anzDF3V2huqqBDmZtMtmm.jpg',
                'display_position' => 2,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:17:16',
                'updated_at' => '2025-08-23 01:17:16',
            ],
            [
                'id' => 11,
                'type' => 4,
                'icon' => 'stretched-link',
                'title' => 'Feeding Jejunostomy',
                'short_description' => 'Diagnosis, surgery, and chemotherapy support for breast cancer.',
                'description' => 'Diagnosis, surgery, and chemotherapy support for breast cancer.',
                'storage_type' => '1',
                'file_path' => 'uploads/IFjQOcdYTisCtm8h5tp8hrd4D0CoX1DZ8zTpxMZQ.jpg',
                'display_position' => 1,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:18:13',
                'updated_at' => '2025-08-23 01:18:13',
            ],
            [
                'id' => 12,
                'type' => 4,
                'icon' => 'stretched-link',
                'title' => 'Esophageal Stenting',
                'short_description' => 'Medical and surgical services for colon cancer.',
                'description' => 'Medical and surgical services for colon cancer.',
                'storage_type' => '1',
                'file_path' => 'uploads/Bii70dNnqLI2VLQ6XlmQHPdRYtrJCZl6Dku5Cwsp.jpg',
                'display_position' => 2,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:20:20',
                'updated_at' => '2025-08-23 01:20:20',
            ],
            [
                'id' => 13,
                'type' => 5,
                'icon' => '',
                'title' => 'Medical and surgical services for colon cancer.',
                'short_description' => '-',
                'description' => 'Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.',
                'storage_type' => '1',
                'file_path' => 'uploads/Rdnh7UFNL0BtiYkt6nqC3wd8rT3NCUDsjqQDT9S7.jpg',
                'display_position' => 1,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:21:54',
                'updated_at' => '2025-08-23 01:21:54',
            ],
            [
                'id' => 14,
                'type' => 5,
                'icon' => '',
                'title' => 'Feugiat scelerisque varius morbi enim nunc faucibus?',
                'short_description' => '-',
                'description' => 'Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.',
                'storage_type' => '1',
                'file_path' => 'uploads/zJNOtWoEGCj9pIk2PzYUcUYf3Qti35BU5atGwHXd.jpg',
                'display_position' => 2,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:22:29',
                'updated_at' => '2025-08-23 01:22:29',
            ],
            [
                'id' => 15,
                'type' => 6,
                'icon' => '',
                'title' => 'Saul Goodman',
                'short_description' => 'Entrepreneur',
                'description' => 'Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.',
                'storage_type' => '1',
                'file_path' => 'uploads/BfmrXqc4p7YMny9mekpwMhpex3C2NqpFIyfq7iBl.jpg',
                'display_position' => 1,
                'is_highlight_item' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:24:29',
                'updated_at' => '2025-08-23 01:24:29',
            ],
        ]);

        DB::table('doctors')->insert([
            [
                'id' => 1,
                'name' => 'Dr. Md. Ashiqur Rahman',
                'picture' => 'doctors/VoF5Vt5XyTsNTcGK9Snl9sM9NEdCjQ89THbD7pcL.jpg',
                'qualifications' => 'MBBS (CMC),FCPS(Surgery) MS (Surgical Oncology), FACS (America)',
                'special_training' => 'Special Training: Tata Memorial Hospital, Mumbai, India & UKM Hospital, Malaysia',
                'positions' => 'Associate Professor, Institute of Cancer Research & Hospital, Dhaka',
                'doctor_profile' => 'Dr. Md. Ashiqur Rahman\nAssociate Professor & Surgical Oncologist\n\nDr. Md. Ashiqur Rahman is a highly qualified cancer surgeon (surgical oncologist) with extensive experience in the surgical management of different types of cancers.\n\nHe completed his MBBS from Chittagong Medical College, followed by FCPS in General Surgery (2011). To further specialize, he obtained his MS in Surgical Oncology (2018) from Bangabandhu Sheikh Mujib Medical University (BSMMU).\n\nDr. Ashique has also received advanced training in cancer surgery from two world-renowned centers: Tata Memorial Cancer Hospital, Mumbai, India, and UKM Hospital, Malaysia.\n\nHe is currently serving as an Associate Professor of Surgical Oncology, actively involved in patient care, teaching, and research. He has contributed significantly to medical literature with over 15 publications, including 6 in international journals and 10 in national journals.\n\nAreas of Expertise\nDr. Ashique specializes in the surgical treatment of:\n\nBreast Cancer\nGastric (Stomach) Cancer\nColorectal Cancer\nSarcoma (soft tissue and bone)\nHepatobiliary Cancer (liver, gallbladder, bile ducts)\nSkin Cancer\nTesticular Cancer\nChambers & Consultation\nMain Chamber: Health and Hospital, Green Road, Panthapath, Dhaka\nWeekly Chamber (Friday): Nova Hospital, Jashore\nPhilosophy of Care\n\nDr. Ashique believes in a patient-centered approach, combining advanced surgical techniques with compassion and personalized care. His goal is to provide the best possible outcomes and hope for cancer patients throughout their treatment journey.',
                'mobile' => '+880 1711-196458',
                'email' => '',
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'linkedin' => NULL,
                'tiktok' => NULL,
                'youtube' => NULL,
                'display_position' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 00:53:09',
                'updated_at' => '2025-08-23 01:00:17',
            ],
            [
                'id' => 2,
                'name' => 'Dr. Mitun Kumar Mallick',
                'picture' => NULL,
                'qualifications' => 'MBBS, BCS(Health), MS (Surgical Oncology)',
                'special_training' => 'Special Training: Genito Unrinary Surgical Oncology Institute of Cancer Research & Hospital, Dhaka',
                'positions' => 'Surgical Oncology, Institute of Cancer Research & Hospital, Dhaka',
                'doctor_profile' => 'Content is being Updated',
                'mobile' => '018',
                'email' => '',
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'linkedin' => NULL,
                'tiktok' => NULL,
                'youtube' => NULL,
                'display_position' => 2,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:01:45',
                'updated_at' => '2025-08-23 01:02:03',
            ],
            [
                'id' => 3,
                'name' => 'Dr. Muhammad Syeef Khalid',
                'picture' => NULL,
                'qualifications' => 'MBBS, MS (Surgical Oncology), MRCS (England)',
                'special_training' => 'Special Training: Endoscopy and Colonscopy Basic Laparospic Surgery',
                'positions' => 'Ex-Registrar, Surgical Oncology, Institute of Cancer Research & Hospital, Dhaka\nLife Member, Society of Endro-laparoscopic Surgeons of Bangladesh',
                'doctor_profile' => 'content is being updated.',
                'mobile' => '018',
                'email' => '',
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'linkedin' => NULL,
                'tiktok' => NULL,
                'youtube' => NULL,
                'display_position' => 3,
                'is_active' => 1,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 01:03:04',
                'updated_at' => '2025-08-23 01:03:04',
            ],
        ]);

        DB::table('company_infos')->insert([
            [
                'id' => 1,
                'name' => 'Hope centre for cancer surgery and research',
                'slug' => 'HOPE',
                'logo' => 'company_logos/lKY5SG83nulRVsFxcHeEtR7i2in3aEYPku2Wr0pr.jpg',
                'address' => 'Health & Hope Hospital 152/2/G Panthapath, Dhaka-1205',
                'mobile' => '+880 155 6313 500',
                'email' => 'info@hopecancersurgery.com',
                'fb' => NULL,
                'twitter' => NULL,
                'linkedin' => NULL,
                'tiktok' => NULL,
                'youtube' => NULL,
                'created_by' => NULL,
                'created_ip' => NULL,
                'updated_by' => NULL,
                'updated_ip' => NULL,
                'created_at' => '2025-08-23 07:43:28',
                'updated_at' => '2025-08-23 07:46:36',
            ],
        ]);
    }
}
